---
apiVersion: v2
name: vh-video-api
home: https://github.com/hmcts/vh-video-api
version: 0.0.22
description: Helm Chart for Video Hearing video-api
maintainers:
  - name: VH Devops 
dependencies:
  - name: java
    version: 3.8.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
